services:
  nostr-relay:
    build: .
    container_name: nostr-relay
    ports:
      - "8000:7777"
    user: "100:100"
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/usr/src/app/db:Z
    stdin_open: true
    tty: true
    restart: unless-stopped

